"""
00 — How to run a Python script with uv.

NOT GRADED. Nothing here is homework and there are no blanks to fill in. This
script exists so that `uv run` stops being a magic incantation before you start
on 01.

    uv run 00_uv_tutorial.py
    uv run 00_uv_tutorial.py --name Ada
    uv run 00_uv_tutorial.py --times 5

Run the first one now. Then come back and read the rest of this file, because
the whole point is that the output changes depending on what you type and what
you edit.

(Unlike 01 through 05, this file is hand-written rather than generated by
make_homework.py — it has no answer key, because it has no answer.)
"""

import argparse
import pathlib
import sys


# ---------------------------------------------------------------------------
# CHANGE ME — edit this line, save the file, and run the script again.
#
# That is the entire loop you will use for the rest of the course: edit, save,
# re-run. You do not reinstall anything, you do not restart anything. uv has
# already built the environment and `uv run` just uses it.
# ---------------------------------------------------------------------------
GREETING = "Hello"


def show_which_python():
    """
    Prove that `uv run` is using the project's environment, not your system one.

    This is the thing most people find confusing, so it is worth seeing rather
    than being told: `uv run` puts a specific Python on the front of the path
    for the duration of one command.
    """
    exe = pathlib.Path(sys.executable)
    in_venv = ".venv" in exe.parts

    print("  Which Python is running this?")
    print(f"    {exe}")
    if in_venv:
        print("    ^ that '.venv' is the environment uv built for this folder.")
        print("      You never activated it. `uv run` did that for you.")
    else:
        print("    ^ this is NOT inside a .venv, so you are probably running")
        print("      `python 00_uv_tutorial.py` instead of `uv run 00_uv_tutorial.py`.")
        print("      This file still works, because it only uses the standard library.")
        print("      Whether 01_lr.py works depends on whether this Python happens to")
        print("      have numpy — which is exactly the uncertainty `uv run` removes.")
    print()


def show_installed_packages():
    """
    Show that `uv sync` really did install the course dependencies.

    numpy is the one every exercise needs. matplotlib is optional and only the
    --plot flags use it, so a missing matplotlib is not a problem.
    """
    print("  What did `uv sync` install?")
    for name in ("numpy", "matplotlib"):
        try:
            module = __import__(name)
            version = getattr(module, "__version__", "unknown version")
            print(f"    {name:<12} {version}")
        except ImportError:
            print(f"    {name:<12} NOT INSTALLED — run `uv sync` in this folder")
    print()


def show_arguments(args):
    """
    Demonstrate command-line flags, which every other script in this folder uses.

    `uv run 01_lr.py --plot` passes --plot through to the script. uv does not
    consume it; everything after the filename belongs to your program.
    """
    print("  What did you type on the command line?")
    print(f"    --name  = {args.name!r}")
    print(f"    --times = {args.times}")
    if args.name == "world" and args.times == 1:
        print("    (those are the defaults — you did not pass any flags)")
        print("    Try:  uv run 00_uv_tutorial.py --name Ada --times 3")
    print()


def main():
    # argparse turns "--name Ada" into args.name == "Ada". Every script in this
    # folder sets its flags up the same way; `--help` always lists them.
    parser = argparse.ArgumentParser(
        description="A tour of running Python scripts with uv. Not graded."
    )
    parser.add_argument("--name", default="world", help="who to greet")
    parser.add_argument("--times", type=int, default=1, help="how many times to greet")
    args = parser.parse_args()

    if args.times < 1:
        raise SystemExit("--times must be at least 1")

    print("=" * 66)
    print("  00 — RUNNING PYTHON WITH UV")
    print("=" * 66)
    print()

    show_which_python()
    show_installed_packages()
    show_arguments(args)

    print("  The actual output:")
    for _ in range(args.times):
        print(f"    {GREETING}, {args.name}!")
    print()

    # ┌─ TRY THIS ──────────────────────────────────────────────────────────────
    # │ Four things, in order. Each takes about ten seconds.
    # │
    # │   1. Change GREETING near the top of this file to something else.
    # │      Save. Run `uv run 00_uv_tutorial.py` again. The output changed —
    # │      no reinstall, no restart.
    # │
    # │   2. Run `uv run 00_uv_tutorial.py --name Ada --times 3`.
    # │      Flags after the filename go to the script, not to uv.
    # │
    # │   3. Run `uv run 00_uv_tutorial.py --help`.
    # │      argparse prints the flags for free. This works on 01 through 05
    # │      too, and is the fastest way to see what a script accepts.
    # │
    # │   4. Run `python 00_uv_tutorial.py` — no `uv run`. Compare the Python
    # │      path it prints against the one from step 1. Two different Pythons,
    # │      same file.
    # │
    # │      Now try `python 01_lr.py`. On most machines that fails with
    # │      ModuleNotFoundError, because your system Python never got numpy.
    # │      On some it works, because numpy happens to be installed globally.
    # │      "Happens to be" is the problem: `uv run` makes it certain, and
    # │      identical on your laptop, a classmate's, and the grader's.
    # └──────────────────────────────────────────────────────────────────────────

    print("  WHAT TO REMEMBER")
    print()
    print("    uv sync                 build the environment. Once per clone.")
    print("    uv run <script.py>      run a script inside that environment.")
    print("    uv run <script> --flag  flags after the filename go to the script.")
    print()
    print("    You never activate anything. There is no `source .venv/bin/activate`")
    print("    in this course. If a command fails with ModuleNotFoundError, the")
    print("    first thing to check is whether you forgot the `uv run` prefix.")
    print()
    print("  Next: open 01_lr.py and run it. It will stop at a NotImplementedError,")
    print("  which is the assignment starting — see README.md.")
    print("=" * 66)


if __name__ == "__main__":
    main()
