"""
make_homework.py — generate the student scripts and the released solutions
from the answer keys.

INSTRUCTOR TOOL. The `answer/` directory it reads is gitignored and is not
distributed, so running this from a fresh clone will correctly report that it
found no answer keys. Students do not need this file.

    uv run make_homework.py

Each answer script in `answer/` marks its solution with a pair of sentinels:

    # BEGIN SOLUTION: short description
    ...the code students must write...
    # END SOLUTION

One source, two outputs:

    answer/01_lr_ans.py ─┬─→ 01_lr.py                     the student script —
                         │                                every marked block
                         │                                becomes a stub
                         │
                         └─→ solutions/01_lr_solution.py  the released answer —
                                                          the marker comments go
                                                          and the code stays

Everything else — the data, the metrics, the printing, the YOUR TASK
instructions above each block — is byte-for-byte identical across all three. In
the solution the task box therefore ends up sitting directly above the code that
answers it, which is the point: it reads as completed homework rather than as a
fresh tutorial that never mentions there was a question.

Generating rather than hand-writing matters: fix a bug in an answer key and both
outputs pick it up on the next run, so the versions cannot drift apart.

The two outputs have opposite release rules. The student scripts are committed
and always public. The solutions are gitignored and get published one at a time,
by hand, once each homework's deadline has passed — see the "Solutions" section
of README.md for the release and un-release commands.
"""

import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent
ANSWER_DIR = HERE / "answer"
SOLUTION_DIR = HERE / "solutions"

BEGIN = re.compile(r'^(\s*)#\s*BEGIN SOLUTION:?\s*(.*)$')
END = re.compile(r'^\s*#\s*END SOLUTION\s*$')

# Stamped into every generated solution, immediately under the module docstring.
SOLUTION_BANNER = """\
# ---------------------------------------------------------------------------
# SOLUTION. Published only after this homework's deadline has passed.
#
# This is the student script with the blanks filled in. The YOUR TASK boxes are
# left exactly where they were, so each one now sits directly above the code
# that answers it: read the box, then read the answer, then go back to your own
# attempt and compare the two.
#
# Generated by make_homework.py — edit the answer key and regenerate. Changes
# made directly to this file are silently undone on the next run.
# ---------------------------------------------------------------------------
"""


def blank_out(lines, source_name):
    """Replace every BEGIN/END SOLUTION block with a stub. Returns (lines, count)."""
    out, i, replaced = [], 0, 0

    while i < len(lines):
        m = BEGIN.match(lines[i])
        if not m:
            out.append(lines[i])
            i += 1
            continue

        indent, description = m.group(1), (m.group(2).strip() or "the missing code")

        # Find the matching END, so an unbalanced marker is a loud failure
        # rather than a file that silently swallows the rest of itself.
        j = i + 1
        while j < len(lines) and not END.match(lines[j]):
            j += 1
        if j >= len(lines):
            raise SystemExit(f"{source_name}: 'BEGIN SOLUTION' at line {i + 1} has no 'END SOLUTION'")

        out.append(f'{indent}# YOUR CODE HERE — {description}\n')
        out.append(f'{indent}# Delete the raise below once you have written it.\n')
        out.append(f'{indent}raise NotImplementedError(\n')
        out.append(f'{indent}    "Homework: write {description}. "\n')
        out.append(f'{indent}    "See the YOUR TASK box just above for the steps."\n')
        out.append(f'{indent})\n')

        replaced += 1
        i = j + 1

    return out, replaced


def strip_sentinels(lines, source_name):
    """
    Drop the BEGIN/END SOLUTION marker lines and keep the code between them.

    The mirror image of blank_out(): same sentinels, opposite decision about
    what to throw away. Returns (lines, count).
    """
    out, kept, open_at = [], 0, None

    for n, line in enumerate(lines, start=1):
        if BEGIN.match(line):
            if open_at is not None:
                raise SystemExit(
                    f"{source_name}: 'BEGIN SOLUTION' at line {n} while the one at "
                    f"line {open_at} is still open"
                )
            open_at, kept = n, kept + 1
            continue
        if END.match(line):
            if open_at is None:
                raise SystemExit(f"{source_name}: 'END SOLUTION' at line {n} closes nothing")
            open_at = None
            continue
        out.append(line)

    if open_at is not None:
        raise SystemExit(f"{source_name}: 'BEGIN SOLUTION' at line {open_at} has no 'END SOLUTION'")

    return out, kept


def insert_after_docstring(lines, block, source_name):
    """
    Put `block` directly below the module docstring.

    The docstring opens on the first line and closes on the next line that is
    nothing but triple quotes, so locating it is a scan rather than a parse.
    """
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == '"""':
            return lines[: i + 1] + ["\n"] + block.splitlines(keepends=True) + lines[i + 1 :]
    raise SystemExit(f"{source_name}: could not find the end of the module docstring")


def convert(answer_path):
    """Turn one answer file into its homework counterpart."""
    lines = answer_path.read_text(encoding="utf-8").splitlines(keepends=True)
    lines, replaced = blank_out(lines, answer_path.name)
    if replaced == 0:
        raise SystemExit(f"{answer_path.name}: no BEGIN SOLUTION block found — nothing to blank")

    text = "".join(lines)
    # The header says ANSWER KEY; the student copy should not.
    text = text.replace("   [ANSWER KEY]\n", "\n", 1)
    # Reports and figures should not overwrite the answer key's output files.
    text = text.replace("_ans.py", ".py")
    # The folder is a uv project, so that is how the usage lines should read.
    text = text.replace("\n    python ", "\n    uv run ")

    out_path = HERE / answer_path.name.replace("_ans.py", ".py")
    out_path.write_text(text, encoding="utf-8")
    return out_path, replaced


def make_solution(answer_path):
    """Turn one answer file into the copy released after the deadline."""
    lines = answer_path.read_text(encoding="utf-8").splitlines(keepends=True)
    lines, kept = strip_sentinels(lines, answer_path.name)
    if kept == 0:
        raise SystemExit(f"{answer_path.name}: no BEGIN SOLUTION block found — nothing to release")

    lines = insert_after_docstring(lines, SOLUTION_BANNER, answer_path.name)

    text = "".join(lines)
    # The header said ANSWER KEY, which is the private copy; this one is public.
    text = text.replace("   [ANSWER KEY]\n", "   [SOLUTION]\n", 1)
    text = text.replace("_ans.py", "_solution.py")
    # Solutions sit one directory down, so the usage lines have to say so —
    # they are run from notebooks/homework like everything else.
    text = text.replace("\n    python ", "\n    uv run solutions/")

    SOLUTION_DIR.mkdir(exist_ok=True)
    out_path = SOLUTION_DIR / answer_path.name.replace("_ans.py", "_solution.py")
    out_path.write_text(text, encoding="utf-8")
    return out_path, kept


def main():
    answers = sorted(ANSWER_DIR.glob("*_ans.py"))
    if not answers:
        raise SystemExit(f"no *_ans.py files found in {ANSWER_DIR}")

    print(f"Generating from {len(answers)} answer key(s):\n")
    for a in answers:
        student, n = convert(a)
        solution, k = make_solution(a)
        print(f"  {a.name:<22} -> {student.name:<18} ({n} block(s) blanked)")
        print(f"  {'':<22} -> solutions/{solution.name:<18} ({k} block(s) kept)")

    print(f"\nWrote {len(answers)} student script(s) to {HERE}")
    print(f"Wrote {len(answers)} solution(s) to {SOLUTION_DIR}")
    print(
        "\nThe solutions are gitignored. Releasing one is a deliberate, manual\n"
        "step — see the 'Solutions' section of README.md."
    )


if __name__ == "__main__":
    sys.exit(main())
